#!/bin/bash

# Colors for output
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
NC='\033[0m' # No Color

echo -e "${BLUE}🎹 Corne Keyboard Firmware Build Scripts${NC}"
echo -e "${CYAN}=======================================${NC}"
echo ""
echo -e "${YELLOW}🐳 Docker (Recommended - No manual setup required):${NC}"
echo ""
echo -e "${GREEN}just docker-setup${NC}          - Initialize ZMK workspace using Docker"
echo -e "${GREEN}just docker-build${NC}          - Build firmware using Docker"
echo -e "${GREEN}just docker-shell${NC}          - Open shell in Docker container"
echo -e "${GREEN}just docker-clean${NC}          - Clean Docker build artifacts"
echo ""
echo -e "${YELLOW}Available scripts:${NC}"
echo ""
echo -e "${GREEN}just setup${NC}                 - Initialize ZMK workspace (run first time)"
echo -e "${GREEN}just build${NC}                 - Build firmware for both sides"
echo -e "${GREEN}just build-left${NC}            - Build only left side"
echo -e "${GREEN}just build-right${NC}           - Build only right side"
echo -e "${GREEN}just flash${NC}                 - Auto-detect and flash firmware"
echo -e "${GREEN}just clean${NC}                 - Clean build artifacts"
echo -e "${GREEN}just clean-all${NC}             - Clean everything including firmware"
echo -e "${GREEN}just reset${NC}                 - Reset entire workspace"
echo -e "${GREEN}just quick${NC}                 - Build and flash in one command"
echo -e "${GREEN}just watch${NC}                 - Watch for keymap changes and rebuild"
echo -e "${GREEN}just info${NC}                  - Show build status and info"
echo -e "${GREEN}just validate${NC}              - Validate keymap syntax"
echo ""
echo -e "${YELLOW}Quick start:${NC}"
echo -e "${YELLOW}🐳 Docker (Easy setup):${NC}"
echo -e "  1. ${CYAN}just docker-setup${NC}      # First time setup"
echo -e "  2. ${CYAN}just docker-build${NC}      # Build firmware"
echo -e "  3. ${CYAN}just flash${NC}             # Flash to keyboard"
echo ""
echo -e "${YELLOW}🔧 Native (Manual setup):${NC}"
echo -e "  1. ${CYAN}just setup${NC}             # First time setup (requires SDK)"
echo -e "  2. ${CYAN}just build${NC}             # Build firmware"
echo -e "  3. ${CYAN}just flash${NC}             # Flash to keyboard"
echo ""
echo -e "${YELLOW}Development:${NC}"
echo -e "  ${CYAN}just dev${NC}                  # Clean and build"
echo -e "  ${CYAN}just watch${NC}                # Auto-rebuild on changes"
echo -e "  ${CYAN}just quick${NC}                # Build and flash quickly"
echo ""
echo -e "${YELLOW}Configuration files:${NC}"
echo -e "  📝 config/ferris_rev02.keymap  - Your keymap configuration"
echo -e "  ⚙️  build.yaml                 - Build configuration"
echo ""
echo -e "${YELLOW}Output:${NC}"
echo -e "  📁 firmware/                   - Built firmware files (.uf2)"